### ISSUE TITLE
Build warning spew involving "Skipping generation of prefixed accessor"

### ISSUE THREAD

**Issue by burmako** [openxla/stablehlo#195] opened 2022-09-26 15:31 UTC
```
$ ninja check-stablehlo
ninja: Entering directory `/usr/local/google/home/burmako/stablehlo/build'
[14/42] Building StablehloOps.h.inc...
/usr/local/google/home/burmako/stablehlo/stablehlo/dialect/StablehloOps.td:981:1: note: Skipping generation of prefixed accessor `getOperands` as it overlaps with default one; generating raw form (`operands`) still
def StableHLO_OutfeedOp : StableHLO_Op<"outfeed", []> {
^
/usr/local/google/home/burmako/stablehlo/stablehlo/dialect/StablehloOps.td:981:1: note: Skipping generation of prefixed accessor `getOperands` as it overlaps with default one; generating raw form (`operands`) still
def StableHLO_OutfeedOp : StableHLO_Op<"outfeed", []> {
^
/usr/local/google/home/burmako/stablehlo/stablehlo/dialect/StablehloOps.td:981:1: note: Skipping generation of prefixed accessor `getOperands` as it overlaps with default one; generating raw form (`operands`) still
def StableHLO_OutfeedOp : StableHLO_Op<"outfeed", []> {
^
...
```

**Comment by GleasonK** [comment] 2022-09-26 15:57
Issue is caused by ops that have a `$operands` input argument. Operations by default have a [getOperands](https://mlir.llvm.org/doxygen/classmlir_1_1Operation.html#ac632a7783f8ec353f79c4f17cb188454) function, which causes the prefixed accessor to match the `Operation` method.

```
def StableHLO_OutfeedOp : StableHLO_Op<"outfeed", []> {
  // ...

  let arguments = (ins
    Variadic<HLO_Tensor>:$operands,
    HLO_Token:$token,
    DefaultValuedStrAttr<StrAttr, "">:$outfeed_config
  );
  let results = (outs HLO_Token);
}
```

This warning is only issued if `$operand` is not the only input argument. That is to say, it warns when `operands()` and `getOperands()` would return a different set of arguments. 

Resolving these issues will require renaming `$operands` for these cases. Only issue is, we document these values as `operands` in most places in [XLA Semantics](https://www.tensorflow.org/xla/operation_semantics#reduce), and keeping in sync with these names is not an option with prefixed accessors.

**Comment by GleasonK** [comment] 2022-09-26 18:42
The following operations currently have an input argument named `$operands` that is not the only input argument. They will require renames to squash the build warnings, looking for feedback on the following names:

| Op                     | Proposed Operand Name | C++ Getter Method |
| --------------- | -------------------------- | ------------------ |
| `OutfeedOp`       |  `$data`  |  `getData()`  |
| `SendOp`             |  `$data`  |  `getData()`  |
| `ReduceOp`      |  `$arrays`  |  `getArrays()` |
| `ReduceWindowOp`  |  `$arrays`  |  `getArrays()` |
| `ScatterOp`         |  `$arrays`  |  `getArrays()` |

Alternate design would be to rename them all to something generic but identical like `values`, `input_operands`, or `data_operands`.

(cc: @tpopp, Eugene mentioned on #150 that you may be looking into switching MHLO to use Prefixed instead of Both. Let me know if you have a different mitigation plan for these ops)

**Comment by burmako** [comment] 2022-09-27 05:21
I like the idea to consistently rename everything. How about `inputs`?

Also, let's rename all `$operands`. Even if we can get away without renaming some of them now (e.g. `CustomCallOp::operands`), we may get into trouble in the future if we decide to expand their corresponding ops to include additional operands. Given that we'll be switching from `.operands()` to `.getOperands()` anyway, we might as well switch directly to `.getInputs()` or something and future-proof ourselves.

By the way, from https://mlir.llvm.org/docs/BytecodeFormat/, I see that this change doesn't break compatibility guarantees, so I don't think that it needs to go through the RFC process.

**Closed** 2022-09-29 15:37 UTC
Labels: Build
