### ISSUE TITLE
AllReduce tuple support

### ISSUE THREAD

**Issue by sdasgup3** [openxla/stablehlo#1602] opened 2023-06-09 02:07 UTC
Corresponding MHLO change: https://github.com/tensorflow/mlir-hlo/commit/2b77e6ac263c7a0547a03740a8c6678247c42ef8

**Comment by burmako** [comment] 2023-06-09 02:08
Duplicate of https://github.com/openxla/stablehlo/issues/1370.

**Closed by burmako** 2023-06-09 02:08 UTC
Labels: Integrations, Migrate from MHLO
