### ISSUE TITLE
Move shape function of convolution to shared files

### ISSUE THREAD

**Issue by zhouxin913** [openxla/stablehlo#361] opened 2022-10-18 21:44 UTC
### Request description

As follow up of https://github.com/openxla/stablehlo/pull/360

**Comment by zhouxin913** [comment] 2022-10-21 23:32
blocked by https://github.com/openxla/stablehlo/issues/213

**Comment by burmako** [comment] 2022-11-07 23:23
Duplicate of #270.

**Closed by burmako** 2022-11-07 23:23 UTC
Labels: Type inference
