### ISSUE TITLE
Reduce op should not take ranked init values

### ISSUE THREAD

**Issue by ghpvnist** [openxla/stablehlo#1279] opened 2023-03-06 19:59 UTC
According to the [spec](https://github.com/openxla/stablehlo/blob/main/docs/spec.md#inputs-59), the variadic init values should be scalar, but tests in `infer_stablehlo.mlir`, `ops_stablehlo.mlir`, and `print_reduce.mlir` have ranked tensors. A verification needs to be added for this.

**Comment by burmako** [comment] 2023-03-06 20:02
Thank you for taking the time to document this issue. I think it's a duplicate of #704. Please feel free to reopen if needed.

**Closed by burmako** 2023-03-06 20:02 UTC
Labels: Verification
