### ISSUE TITLE
Missing Type inference for AllGatherOp

### ISSUE THREAD

**Issue by sdasgup3** [openxla/stablehlo#497] opened 2022-11-10 00:54 UTC
The following invalid test will pass without the inference in place
```
func.func @main(%arg0: tensor<128x100x32xf32>) -> tensor<128x100xf32> {
  %0 = "stablehlo.all_gather"(%arg0) {
    all_gather_dim = 0 : i64,
    channel_handle = #stablehlo.channel_handle<handle = 1, type = 0>,
    replica_groups = dense<[[0, 2, 4, 6], [1, 3, 5, 7]]> : tensor<2x4xi64>
  } : (tensor<128x100x32xf32>) -> tensor<128x100xf32>
  func.return %0 : tensor<128x100xf32>
}
```

As per the spec https://www.tensorflow.org/xla/operation_semantics#allgather

`The output shape is the input shape with the all_gather_dim made shard_count times larger.`

**Comment by burmako** [comment] 2022-11-10 05:50
This sounds like a bug in the verifier of AllGatherOp. Implementing type inference for AllGatherOp might help with this (depending on the implementation), but the root cause seems to be in verification. Perhaps let's close this ticket in favor of #491?

**Closed** 2022-11-10 17:17 UTC
Labels: Type inference
